const origins = [
  {
    origin: "Mansa Kingdom",
    language: "Keitan",
    faith: "The Prophet",
    attributeBonus: "agility",
    abilityBonus: "Ride",
  },
  {
    origin: "Tumbutu City State",
    language: "Keitan",
    faith: "The Prophet",
    attributeBonus: "wisdom",
    abilityBonus: "Decipher",
  },
  {
    origin: "Tsugoab Plains",
    language: "Khoi",
    faith: "Cagn",
    attributeBonus: "awareness",
    abilityBonus: "Endurance",
  },
  {
    origin: "Kermo City",
    language: "Khastan",
    faith: "Menhit",
    attributeBonus: "wisdom",
    abilityBonus: "Craft",
  },
  {
    origin: "Mero City",
    language: "Khastan",
    faith: "Horu",
    attributeBonus: "awareness",
    abilityBonus: "Alert",
  },
  {
    origin: "Turkhana Plains",
    language: "Unku",
    faith: "Shaka",
    attributeBonus: "strength",
    abilityBonus: "Sneak",
  },
  {
    origin: "Mbuti Village",
    language: "Bayaka",
    faith: "Mbuti (Mbuti Forest)",
    attributeBonus: "agility",
    abilityBonus: "Survival",
  },
  {
    origin: "Ounsi Forest",
    language: "Oduduwa",
    faith: "Olodu",
    attributeBonus: "soul",
    abilityBonus: "Survival",
  },
  {
    origin: "Olodumare Plains",
    language: "Oduduwa",
    faith: "Olodu",
    attributeBonus: "strength",
    abilityBonus: "Craft metal",
  },
  {
    origin: "Qertassi Temple",
    language: "Khastan",
    faith: "Apademak",
    attributeBonus: "awareness",
    abilityBonus: "Focus",
  },
  {
    origin: "Napoto City",
    language: "Khastan",
    faith: "Piye",
    attributeBonus: "strength",
    abilityBonus: "Endurance",
  },
  {
    origin: "Sebiumeker",
    language: "Khastan",
    faith: "Alara",
    attributeBonus: "soul",
    abilityBonus: "Swim",
  },
];
